name: gazelle_test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  gazelle_core: ^0.2.0
  objectbox: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
